<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PRomda.FileShare</AssemblyName>
    <RootNamespace>PRomda.FileShare</RootNamespace>
    <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
</Project>
